name: Run Tests On Demand

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to checkout and test"
        required: true
        default: "main"
      selphiVersion:
        description: "Selphi version"
        required: false
      selphidVersion:
        description: "Selphid version"
        required: false
      urlBase:
        description: "Base URL"
        required: false
      executionEnvironment:
        description: "Execution environment"
        required: false
        default: "local"
        type: choice
        options:
          - remote
          - local
      projectName:
        description: "Project name"
        required: true
        type: choice
        options:
          - selphi
          - selphid
      buildName:
        description: "Build name"
        required: false
      testsFile:
        description: "Tests file"
        required: true
        type: choice
        options:
          - selphidRegression
          - selphiRegression
      deviceType:
        description: "Device type"
        required: true
        type: choice
        options:
          - android
          - ios
          - windows
          - macos
      env:
        description: "Environment"
        required: true
        type: choice
        options:
          - IO
          - QA
          - LOCALHOST
      engine:
        description: "Engine type"
        required: true
        type: choice
        options:
          - MB
          - FirstParty
      test:
        description: "Specific test"
        required: false

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: "Install dependencies with Bun"
        run: bun i

      - name: "Run tests"
        run: 
          echo "bun run cliAuto $params"
