name: Run Tests

on:
  workflow_dispatch:
    inputs:
      widget:
        description: "Widget"
        required: true
        default: selphi
        type: choice
        options:
          - selphi
          - selphid
      widgetVersion:
        description: "Widget version"
        required: true
        default: "6.8.0"
      executionEnvironment:
        description: "Execution environment"
        required: true
        default: remote
        type: choice
        options:
          - remote
          - local
      projectName:
        description: "Project name"
        required: true
        default: action
      buildName:
        description: "Build name"
        required: false
        default: testingFromAction
      testsFile:
        description: "Tests file"
        required: true
        type: choice
        options:
          - regression
          - compatibility
          - examples
      deviceType:
        description: "Device type"
        required: true
        type: choice
        default: android
        options:
          - android
          - ios
          - windows
          - macos
      env:
        description: "Environment"
        required: true
        type: choice
        default: QA
        options:
          - QA
          - IO
          - LOCALHOST
      engine:
        description: "Engine type"
        required: true
        type: choice
        default: MB
        options:
          - MB
          - FirstParty
      test:
        description: "Specific test"
        required: false

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
 
      - name: "Install dependencies with npm"
        run: echo "bun i"

      - name: "Run tests"
        run: |          
          params=""
          params="$params -selphiVersion ${{ github.event.inputs.widgetVersion }}"
          params="$params -selphidVersion ${{ github.event.inputs.widgetVersion }}"
          params="$params -executionEnvironment ${{ github.event.inputs.executionEnvironment }}"
          params="$params -projectName ${{ github.event.inputs.widget }}_${{ github.event.inputs.testsFile }}_${{ github.event.inputs.projectName }}"
          params="$params -deviceType ${{ github.event.inputs.deviceType }}"
          params="$params -env ${{ github.event.inputs.env }}"
          params="$params -engine ${{ github.event.inputs.engine }}"
          params="$params -testsFile ${{ github.event.inputs.widget }}${{ github.event.inputs.testsFile }}"
          if [ -n "${{ github.event.inputs.buildName }}" ]; then
            params="$params -buildName ${{ github.event.inputs.buildName }}"
          fi
          
          if [ -n "${{ github.event.inputs.test }}" ]; then
            params="$params -test ${{ github.event.inputs.test }}"
          fi
          echo "npm run cliAuto $params"

