
name: E2E Tests

on:
  push:
  # schedule:
  #   - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  e2e_tests:
    needs: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        #os: [ubuntu-20.04, windows-latest, macos-10.15]
        os: [windows-latest]

    steps:
      - name: install maven dependencies
        run: mvn install

      - name: launch all tests high
        run: mvn clean test

