
name: E2E Tests

on:
  push:
  # schedule:
  #   - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  e2e_tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        #os: [ubuntu-20.04, windows-latest, macos-10.15]
        os: [windows-latest]

    steps:
      - name: launch all tests high
        run: mvn clean test
        working-directory: ./
        continue-on-error: true

